Add goupdate command

diff --git a/templates/golang.sh.erb b/templates/golang.sh.erb
--- a/templates/golang.sh.erb
+++ b/templates/golang.sh.erb
@@ -3,3 +3,17 @@ GOROOT="<%= @boxen_home %>/go"
 PATH="$GOPATH/bin:$GOROOT/bin:$PATH"
 GO15VENDOREXPERIMENT=1
 export GOPATH PATH GOROOT GO15VENDOREXPERIMENT
+
+# This function will run go get on every path defined by
+# go_binaries in order to update installed depdendant go
+# libaries
+function goupdate() {
+  echo "Updating go binaries and placing them in $GOPATH/bin"
+  for GO_PATH in "<%= @go_binaries %>"; do
+    go get -u "$GO_PATH"
+    if [ $? -ne 0 ]; then
+      echo "Unable to update $GO_PATH"
+    fi
+  done
+  echo "Finished updating go binaries"
+}
